[build]
  base = "web-app/"
  publish = "build/"
  command = "npm run build"

[functions]
  directory = "web-app/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200